version: "2"
networks:
  my-network:
    driver: bridge
    
services:
  backend:
    # tty: true
    restart: unless-stopped
    build:
      context: .
    ports:
      - "3000:3000"
    links:
      - db
    networks:
      - my-network
    

  db:
    image: mongo:latest
    hostname: mongodbserver
    environment:
      - HOME=/data/db
    volumes:
      - /var/lib/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - my-network
    
volumes:
  static_volume: {}